import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/Home.module.css";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta 
        
            name="keywords"
            content="java script , html , css"
        />
        
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main>

          <h1>titulo do site</h1>

          <p>paragrafo adicionado</p>

          <aside>
              temos mais uma alteração
          </aside>

          <p>coloquei um paragrafo com mais uma alteração</p>

          <div>inclusao de uma ddiv sem paragrafo</div>

          <i>inclui a tag i</i>

          <p>lorem lorem isum </p>

          <div style={{color:'red'}}>

              <i>i</i>
              <i>i</i>
              <i>i</i>
              <i>i</i>
              <i>i</i>

              
          </div>

      </main>
    </>
  );
}
